name: Pull request into release branch exists

on: 
  pull_request:
    branches:
      - dev
    types: [opened, reopened, synchronize]

jobs:
  pre-release-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12' 

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: execute py script 
        env:
          GITHUB_BOT_TOKEN: ${{ secrets.FINE_GRAINED_TOKEN }}
        run: python python/check-pr-into-release-exists.py
