name: Run the Action on each commit

on: workflow_dispatch

jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%d-%m-%Y')" >> $GITHUB_ENV
      - name: Create Pull Request
        run: gh pr create -B prod -H dev --title 'pre_release-'$NOW --body 'Created by Github action' -l automated -r djigitlike -r KrisAce 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
