name: Run the Action on each commit

on:
  push:
    branches:
      - dev

jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      # - name: Set current date as env variable
      #   run: echo "NOW=$(date +'%d-%m-%Y')" >> $GITHUB_ENV
      - name: Create Pull Request
        run: gh pr create -B prod -H dev --title 'pre_release' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
