name: jenkins build success

on:
  repository_dispatch:
    types: [test_result]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.client_payload.name }}"
