name: Update checking status for PRs into dev

on:
  pull_request:
    branches:
      - dev
    types: [opened, reopened, close]


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        if: startsWith(github.base_ref, 'release') 
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12' 

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: execute py script 
        run: python script2.py
